{% set name = "frictionless" %}
{% set version = "3.44.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13d06da6e800de787c7a5b85bf05eca0d9da1af791514e1edda989eb830faf30

build:
  number: 0
  entry_points:
    - frictionless = frictionless.__main__:program
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - petl >=1.6
    - pyyaml >=5.3
    - isodate >=0.6
    - chardet >=3.0
    - requests >=2.10
    - jsonschema >=2.5
    - simpleeval >=0.9
    - stringcase >=1.2
    - typer[all] >=0.3
    - validators >=0.18
    - python-slugify >=1.2
    - python-dateutil >=2.8


test:
  imports:
    - frictionless
  commands:
    - frictionless --help
    - pip check
  requires:
    - pip

about:
  home: http://github.com/frictionlessdata/frictionless-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Frictionless is a framework to describe, extract, validate, and transform tabular data

extra:
  recipe-maintainers:
    - roll
